//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonJT_Web.Resources.Gender.QuA.Sex {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonJT_Web.Resources.Gender.QuA.Sex.DE", typeof(DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitmachen! Lass uns feiern! ähnelt.
        /// </summary>
        internal static string A_11_1 {
            get {
                return ResourceManager.GetString("A_11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dich freuen, neue Bars kennenzulernen. ähnelt.
        /// </summary>
        internal static string A_11_2 {
            get {
                return ResourceManager.GetString("A_11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dich unbehaglich fühlen. ähnelt.
        /// </summary>
        internal static string A_11_3 {
            get {
                return ResourceManager.GetString("A_11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insgeheim aufgeregt sein, denn du wolltest schon immer mal in eine Schwulenbar gehen! ähnelt.
        /// </summary>
        internal static string A_11_4 {
            get {
                return ResourceManager.GetString("A_11_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kommt auf den Jungen an. ähnelt.
        /// </summary>
        internal static string A_15_1 {
            get {
                return ResourceManager.GetString("A_15_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das männliche Auftreten (oder: Der Bart udgl.). ähnelt.
        /// </summary>
        internal static string A_15_2 {
            get {
                return ResourceManager.GetString("A_15_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein süßes Gesicht. ähnelt.
        /// </summary>
        internal static string A_15_3 {
            get {
                return ResourceManager.GetString("A_15_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nichts. Warum auch? ähnelt.
        /// </summary>
        internal static string A_15_4 {
            get {
                return ResourceManager.GetString("A_15_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Da ich mir sicher gehen möchte. ähnelt.
        /// </summary>
        internal static string A_2_1 {
            get {
                return ResourceManager.GetString("A_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einfach nur zum Spaß. ähnelt.
        /// </summary>
        internal static string A_2_2 {
            get {
                return ResourceManager.GetString("A_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_2_3 {
            get {
                return ResourceManager.GetString("A_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_2_4 {
            get {
                return ResourceManager.GetString("A_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das könnte schon passieren, ja. ähnelt.
        /// </summary>
        internal static string A_21_1 {
            get {
                return ResourceManager.GetString("A_21_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nee, wieso das denn? Ich rede einfach normal mit ihm. ähnelt.
        /// </summary>
        internal static string A_21_2 {
            get {
                return ResourceManager.GetString("A_21_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ziemlich sicher. ähnelt.
        /// </summary>
        internal static string A_21_3 {
            get {
                return ResourceManager.GetString("A_21_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_21_4 {
            get {
                return ResourceManager.GetString("A_21_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dich freuen. Du bist dabei! ähnelt.
        /// </summary>
        internal static string A_22_1 {
            get {
                return ResourceManager.GetString("A_22_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Etwas verwirrt sein, aber wahrscheinlich mitmachen! ähnelt.
        /// </summary>
        internal static string A_22_2 {
            get {
                return ResourceManager.GetString("A_22_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Niemals. Ich mag nur das andere Geschlecht! ähnelt.
        /// </summary>
        internal static string A_22_3 {
            get {
                return ResourceManager.GetString("A_22_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitmachen, das Geschlecht der Person ist mir egal. ähnelt.
        /// </summary>
        internal static string A_22_4 {
            get {
                return ResourceManager.GetString("A_22_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich fühle mich schrecklich, wenn ich ihnen nur zuhöre. ähnelt.
        /// </summary>
        internal static string A_25_1 {
            get {
                return ResourceManager.GetString("A_25_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich beteilige mich nicht, sie haben ein Recht auf ihre eigene Meinung ähnelt.
        /// </summary>
        internal static string A_25_2 {
            get {
                return ResourceManager.GetString("A_25_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich diskutiere mit ihnen ähnelt.
        /// </summary>
        internal static string A_25_3 {
            get {
                return ResourceManager.GetString("A_25_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich schließe mich ihnen gerne an ähnelt.
        /// </summary>
        internal static string A_25_4 {
            get {
                return ResourceManager.GetString("A_25_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string A_28_1 {
            get {
                return ResourceManager.GetString("A_28_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string A_28_2 {
            get {
                return ResourceManager.GetString("A_28_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mit offenem Profil ähnelt.
        /// </summary>
        internal static string A_28_3 {
            get {
                return ResourceManager.GetString("A_28_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_28_4 {
            get {
                return ResourceManager.GetString("A_28_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, meistens. ähnelt.
        /// </summary>
        internal static string A_29_1 {
            get {
                return ResourceManager.GetString("A_29_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, ich hatte mal Interesse. ähnelt.
        /// </summary>
        internal static string A_29_2 {
            get {
                return ResourceManager.GetString("A_29_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein. ähnelt.
        /// </summary>
        internal static string A_29_3 {
            get {
                return ResourceManager.GetString("A_29_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_29_4 {
            get {
                return ResourceManager.GetString("A_29_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_3_1 {
            get {
                return ResourceManager.GetString("A_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_3_2 {
            get {
                return ResourceManager.GetString("A_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_3_3 {
            get {
                return ResourceManager.GetString("A_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_3_4 {
            get {
                return ResourceManager.GetString("A_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bier ähnelt.
        /// </summary>
        internal static string A_30_1 {
            get {
                return ResourceManager.GetString("A_30_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gin ähnelt.
        /// </summary>
        internal static string A_30_2 {
            get {
                return ResourceManager.GetString("A_30_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wein ähnelt.
        /// </summary>
        internal static string A_30_3 {
            get {
                return ResourceManager.GetString("A_30_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sekt ähnelt.
        /// </summary>
        internal static string A_30_4 {
            get {
                return ResourceManager.GetString("A_30_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cocktail ähnelt.
        /// </summary>
        internal static string A_30_5 {
            get {
                return ResourceManager.GetString("A_30_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whiskey ähnelt.
        /// </summary>
        internal static string A_30_6 {
            get {
                return ResourceManager.GetString("A_30_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sia ähnelt.
        /// </summary>
        internal static string A_31_1 {
            get {
                return ResourceManager.GetString("A_31_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miley Cyrus ähnelt.
        /// </summary>
        internal static string A_31_2 {
            get {
                return ResourceManager.GetString("A_31_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bruno Mars ähnelt.
        /// </summary>
        internal static string A_31_3 {
            get {
                return ResourceManager.GetString("A_31_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beonce ähnelt.
        /// </summary>
        internal static string A_31_4 {
            get {
                return ResourceManager.GetString("A_31_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lady Gaga ähnelt.
        /// </summary>
        internal static string A_31_5 {
            get {
                return ResourceManager.GetString("A_31_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Harry Styles ähnelt.
        /// </summary>
        internal static string A_31_6 {
            get {
                return ResourceManager.GetString("A_31_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jennifer Lopez ähnelt.
        /// </summary>
        internal static string A_31_7 {
            get {
                return ResourceManager.GetString("A_31_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_31_8 {
            get {
                return ResourceManager.GetString("A_31_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_4_1 {
            get {
                return ResourceManager.GetString("A_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_4_2 {
            get {
                return ResourceManager.GetString("A_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_4_3 {
            get {
                return ResourceManager.GetString("A_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_4_4 {
            get {
                return ResourceManager.GetString("A_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, ist mir schon öfters passiert. ähnelt.
        /// </summary>
        internal static string A_6_1 {
            get {
                return ResourceManager.GetString("A_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, hatte ich einmal. ähnelt.
        /// </summary>
        internal static string A_6_2 {
            get {
                return ResourceManager.GetString("A_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein, ich gucke meist nur auf die Mädels. ähnelt.
        /// </summary>
        internal static string A_6_3 {
            get {
                return ResourceManager.GetString("A_6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein, die Typen interessieren mich nicht. ähnelt.
        /// </summary>
        internal static string A_6_4 {
            get {
                return ResourceManager.GetString("A_6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich nehme jeden / jede, solange er / sie es mir gut besorgen kann. ähnelt.
        /// </summary>
        internal static string A_8_1 {
            get {
                return ResourceManager.GetString("A_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gibt Grenzen bei Alter, Gewicht und Sauberkeit, die aber fließend sein können, wenn es geil ist. ähnelt.
        /// </summary>
        internal static string A_8_2 {
            get {
                return ResourceManager.GetString("A_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Er oder sie müssen schon attraktiv sein und meinen hohen Ansprüchen genügen. ähnelt.
        /// </summary>
        internal static string A_8_3 {
            get {
                return ResourceManager.GetString("A_8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für Sex muss es zu 100% passen. ähnelt.
        /// </summary>
        internal static string A_8_4 {
            get {
                return ResourceManager.GetString("A_8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, alle meine Fantasien sind übers gleiche Geschlecht. ähnelt.
        /// </summary>
        internal static string A_9_1 {
            get {
                return ResourceManager.GetString("A_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oft. ähnelt.
        /// </summary>
        internal static string A_9_2 {
            get {
                return ResourceManager.GetString("A_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nie. ähnelt.
        /// </summary>
        internal static string A_9_3 {
            get {
                return ResourceManager.GetString("A_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selten. ähnelt.
        /// </summary>
        internal static string A_9_4 {
            get {
                return ResourceManager.GetString("A_9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 31 ähnelt.
        /// </summary>
        internal static string MaxQuestion {
            get {
                return ResourceManager.GetString("MaxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie alt bist du? ähnelt.
        /// </summary>
        internal static string Q_1 {
            get {
                return ResourceManager.GetString("Q_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Würdest du dich freuen, wenn ein homosexueller Arbeitskollege mit dir flirten würde? ähnelt.
        /// </summary>
        internal static string Q_10 {
            get {
                return ResourceManager.GetString("Q_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn deine Freunde beschließen würden, in einer Schwulenbar zu feiern, würdest du? ähnelt.
        /// </summary>
        internal static string Q_11 {
            get {
                return ResourceManager.GetString("Q_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn dich ein Junge berührt (Umarmung o.ä.), gefällt dir das Gefühl? ähnelt.
        /// </summary>
        internal static string Q_12 {
            get {
                return ResourceManager.GetString("Q_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn du einen gutaussenden Jungen siehst, fällt er dir auf und schaust du ihm hinterher? ähnelt.
        /// </summary>
        internal static string Q_13 {
            get {
                return ResourceManager.GetString("Q_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die „Mädels faszinieren mich.“ – Was würdest du zu diesem Satz sagen? ähnelt.
        /// </summary>
        internal static string Q_14 {
            get {
                return ResourceManager.GetString("Q_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was gefällt dir an Jungs besonders? ähnelt.
        /// </summary>
        internal static string Q_15 {
            get {
                return ResourceManager.GetString("Q_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funktioniert dein Gaydar? Erkennst du andere schwule Leute? ähnelt.
        /// </summary>
        internal static string Q_16 {
            get {
                return ResourceManager.GetString("Q_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stell dir vor, jemand des gleichen Geschlechts kommt auf dich zu und küsst dich. Wie ist deine Reaktion? ähnelt.
        /// </summary>
        internal static string Q_17 {
            get {
                return ResourceManager.GetString("Q_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn dir ein hübsches paar entgegen kommt, wer fällt dir als erstes auf? ähnelt.
        /// </summary>
        internal static string Q_18 {
            get {
                return ResourceManager.GetString("Q_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn du ein homosexuelles Paar siehst, das sich küsst, was fühlen Sie dann? ähnelt.
        /// </summary>
        internal static string Q_19 {
            get {
                return ResourceManager.GetString("Q_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warum machst du diesen Test? ähnelt.
        /// </summary>
        internal static string Q_2 {
            get {
                return ResourceManager.GetString("Q_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine hübsche, gute Freundin lädt dich zu ihr nach Hause ein. Was denkst du? ähnelt.
        /// </summary>
        internal static string Q_20 {
            get {
                return ResourceManager.GetString("Q_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du bist auf einer Party und ein heiß aussehender Junge spricht dich an. Wirst du ein bisschen nervös, aufgeregt oder sogar sprachlos? ähnelt.
        /// </summary>
        internal static string Q_21 {
            get {
                return ResourceManager.GetString("Q_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn dein Partner dir einen Dreier mit einem gleichgeschlechtlichen Partner anbieten würde, dann würdest du? ähnelt.
        /// </summary>
        internal static string Q_22 {
            get {
                return ResourceManager.GetString("Q_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hattest du jemals Angst oder hast es nach wievor, deiner Familie von deiner sexuellen oder romantischen Vorlieben zu erzählen? ähnelt.
        /// </summary>
        internal static string Q_23 {
            get {
                return ResourceManager.GetString("Q_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fühlst du dich wohl, wenn du über deine sexuelle Identität sprichst oder dich jemand dazu fragt? ähnelt.
        /// </summary>
        internal static string Q_24 {
            get {
                return ResourceManager.GetString("Q_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was tust du, wenn deine Freunde homophobes Zeugs reden? ähnelt.
        /// </summary>
        internal static string Q_25 {
            get {
                return ResourceManager.GetString("Q_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hast du schon einmal Kleidung des anderen Geschlechts getragen, oder darüber fantasiert? ähnelt.
        /// </summary>
        internal static string Q_26 {
            get {
                return ResourceManager.GetString("Q_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hast du jemals davon geträumt, mit einer Person des gleichen Geschlechts romantisch verliebt zu sein? ähnelt.
        /// </summary>
        internal static string Q_27 {
            get {
                return ResourceManager.GetString("Q_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bist du einer Online-LGBT-Community anonym beigetreten? ähnelt.
        /// </summary>
        internal static string Q_28 {
            get {
                return ResourceManager.GetString("Q_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hast du dir jemals gleichgeschlechtliche Pornografie angesehen? ähnelt.
        /// </summary>
        internal static string Q_29 {
            get {
                return ResourceManager.GetString("Q_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hast du schon mal eine Person des gleichen Geschlechts angesehen und dich auf sexuelle Weise angezogen gefühlt? ähnelt.
        /// </summary>
        internal static string Q_3 {
            get {
                return ResourceManager.GetString("Q_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welches Getränk würdest du trinken? ähnelt.
        /// </summary>
        internal static string Q_30 {
            get {
                return ResourceManager.GetString("Q_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Such dir einen Sänger/Sängerin aus. ähnelt.
        /// </summary>
        internal static string Q_31 {
            get {
                return ResourceManager.GetString("Q_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hast du jemals eine Person des gleichen Geschlechts geküsst? ähnelt.
        /// </summary>
        internal static string Q_4 {
            get {
                return ResourceManager.GetString("Q_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hast du jemals eine Person des anderen Geschlechts geküsst? ähnelt.
        /// </summary>
        internal static string Q_5 {
            get {
                return ResourceManager.GetString("Q_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hast du schon mal einen Jungen oder Mann gesehen, oder sogar mit ihm Kontakt gehabt und dann noch Stunden und Tage danach an ihn gedacht - sein Gesicht oder seine Stimme klang noch lange in deinem Kopf nach.
        ///Leider ist er dann nie wieder aufgetaucht? ähnelt.
        /// </summary>
        internal static string Q_6 {
            get {
                return ResourceManager.GetString("Q_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hattest du schonmal sex fantasien mit dem anderen Geschlecht? ähnelt.
        /// </summary>
        internal static string Q_7 {
            get {
                return ResourceManager.GetString("Q_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie flexibel und tolerant bist du bei der Auswahl deiner Sexualpartner? ähnelt.
        /// </summary>
        internal static string Q_8 {
            get {
                return ResourceManager.GetString("Q_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie oft fantasierst du über das gleiche Geschlecht? ähnelt.
        /// </summary>
        internal static string Q_9 {
            get {
                return ResourceManager.GetString("Q_9", resourceCulture);
            }
        }
    }
}
