//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonJT_Web.Resources.Gender.QuA.Sex {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonJT_Web.Resources.Gender.QuA.Sex.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join in! Let&apos;s party! ähnelt.
        /// </summary>
        internal static string A_11_1 {
            get {
                return ResourceManager.GetString("A_11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get excited about meeting new bars. ähnelt.
        /// </summary>
        internal static string A_11_2 {
            get {
                return ResourceManager.GetString("A_11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feel uncomfortable. ähnelt.
        /// </summary>
        internal static string A_11_3 {
            get {
                return ResourceManager.GetString("A_11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secretly be excited because you&apos;ve always wanted to go to a gay bar! ähnelt.
        /// </summary>
        internal static string A_11_4 {
            get {
                return ResourceManager.GetString("A_11_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depends on the boy. ähnelt.
        /// </summary>
        internal static string A_15_1 {
            get {
                return ResourceManager.GetString("A_15_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The masculine appearance (or: the beard, etc.). ähnelt.
        /// </summary>
        internal static string A_15_2 {
            get {
                return ResourceManager.GetString("A_15_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A cute face. ähnelt.
        /// </summary>
        internal static string A_15_3 {
            get {
                return ResourceManager.GetString("A_15_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nothing. Why also? ähnelt.
        /// </summary>
        internal static string A_15_4 {
            get {
                return ResourceManager.GetString("A_15_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die That could happen, yeah. ähnelt.
        /// </summary>
        internal static string A_21_1 {
            get {
                return ResourceManager.GetString("A_21_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nah, why is that? I just talk to him normally. ähnelt.
        /// </summary>
        internal static string A_21_2 {
            get {
                return ResourceManager.GetString("A_21_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pretty sure. ähnelt.
        /// </summary>
        internal static string A_21_3 {
            get {
                return ResourceManager.GetString("A_21_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_21_4 {
            get {
                return ResourceManager.GetString("A_21_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rejoice. You&apos;re in! ähnelt.
        /// </summary>
        internal static string A_22_1 {
            get {
                return ResourceManager.GetString("A_22_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Be a little confused, but probably in! ähnelt.
        /// </summary>
        internal static string A_22_2 {
            get {
                return ResourceManager.GetString("A_22_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Never. I only like the opposite sex! ähnelt.
        /// </summary>
        internal static string A_22_3 {
            get {
                return ResourceManager.GetString("A_22_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join in, I don&apos;t care about the gender of the person. ähnelt.
        /// </summary>
        internal static string A_22_4 {
            get {
                return ResourceManager.GetString("A_22_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I feel terrible just listening to them. ähnelt.
        /// </summary>
        internal static string A_25_1 {
            get {
                return ResourceManager.GetString("A_25_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I don&apos;t participate, they have a right to their own opinion ähnelt.
        /// </summary>
        internal static string A_25_2 {
            get {
                return ResourceManager.GetString("A_25_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I discuss with them ähnelt.
        /// </summary>
        internal static string A_25_3 {
            get {
                return ResourceManager.GetString("A_25_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I like to join them ähnelt.
        /// </summary>
        internal static string A_25_4 {
            get {
                return ResourceManager.GetString("A_25_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string A_28_1 {
            get {
                return ResourceManager.GetString("A_28_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string A_28_2 {
            get {
                return ResourceManager.GetString("A_28_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With open profile ähnelt.
        /// </summary>
        internal static string A_28_3 {
            get {
                return ResourceManager.GetString("A_28_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_28_4 {
            get {
                return ResourceManager.GetString("A_28_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes, most of the time ähnelt.
        /// </summary>
        internal static string A_29_1 {
            get {
                return ResourceManager.GetString("A_29_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes, I used to be interested. ähnelt.
        /// </summary>
        internal static string A_29_2 {
            get {
                return ResourceManager.GetString("A_29_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string A_29_3 {
            get {
                return ResourceManager.GetString("A_29_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_29_4 {
            get {
                return ResourceManager.GetString("A_29_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beer ähnelt.
        /// </summary>
        internal static string A_30_1 {
            get {
                return ResourceManager.GetString("A_30_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gin ähnelt.
        /// </summary>
        internal static string A_30_2 {
            get {
                return ResourceManager.GetString("A_30_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wein ähnelt.
        /// </summary>
        internal static string A_30_3 {
            get {
                return ResourceManager.GetString("A_30_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sekt ähnelt.
        /// </summary>
        internal static string A_30_4 {
            get {
                return ResourceManager.GetString("A_30_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cocktail ähnelt.
        /// </summary>
        internal static string A_30_5 {
            get {
                return ResourceManager.GetString("A_30_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whiskey ähnelt.
        /// </summary>
        internal static string A_30_6 {
            get {
                return ResourceManager.GetString("A_30_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sia ähnelt.
        /// </summary>
        internal static string A_31_1 {
            get {
                return ResourceManager.GetString("A_31_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miley Cyrus ähnelt.
        /// </summary>
        internal static string A_31_2 {
            get {
                return ResourceManager.GetString("A_31_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bruno Mars ähnelt.
        /// </summary>
        internal static string A_31_3 {
            get {
                return ResourceManager.GetString("A_31_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beonce ähnelt.
        /// </summary>
        internal static string A_31_4 {
            get {
                return ResourceManager.GetString("A_31_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lady Gaga ähnelt.
        /// </summary>
        internal static string A_31_5 {
            get {
                return ResourceManager.GetString("A_31_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Harry Styles ähnelt.
        /// </summary>
        internal static string A_31_6 {
            get {
                return ResourceManager.GetString("A_31_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jennifer Lopez ähnelt.
        /// </summary>
        internal static string A_31_7 {
            get {
                return ResourceManager.GetString("A_31_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string A_31_8 {
            get {
                return ResourceManager.GetString("A_31_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes, has happened to me several times. ähnelt.
        /// </summary>
        internal static string A_6_1 {
            get {
                return ResourceManager.GetString("A_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes, I had once. ähnelt.
        /// </summary>
        internal static string A_6_2 {
            get {
                return ResourceManager.GetString("A_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No, I usually only look at the girls. ähnelt.
        /// </summary>
        internal static string A_6_3 {
            get {
                return ResourceManager.GetString("A_6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No, the guys don&apos;t interest me. ähnelt.
        /// </summary>
        internal static string A_6_4 {
            get {
                return ResourceManager.GetString("A_6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I&apos;ll take anyone / everyone as long as they can give it to me good. ähnelt.
        /// </summary>
        internal static string A_8_1 {
            get {
                return ResourceManager.GetString("A_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are limits on age, weight and cleanliness, but they can be fluid if it&apos;s horny. ähnelt.
        /// </summary>
        internal static string A_8_2 {
            get {
                return ResourceManager.GetString("A_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die He or she must already be attractive and meet my high standards. ähnelt.
        /// </summary>
        internal static string A_8_3 {
            get {
                return ResourceManager.GetString("A_8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For sex it must fit 100%. ähnelt.
        /// </summary>
        internal static string A_8_4 {
            get {
                return ResourceManager.GetString("A_8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes, all my fantasies are about the same sex. ähnelt.
        /// </summary>
        internal static string A_9_1 {
            get {
                return ResourceManager.GetString("A_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Often. ähnelt.
        /// </summary>
        internal static string A_9_2 {
            get {
                return ResourceManager.GetString("A_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Never. ähnelt.
        /// </summary>
        internal static string A_9_3 {
            get {
                return ResourceManager.GetString("A_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rarely. ähnelt.
        /// </summary>
        internal static string A_9_4 {
            get {
                return ResourceManager.GetString("A_9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 31 ähnelt.
        /// </summary>
        internal static string MaxQuestion {
            get {
                return ResourceManager.GetString("MaxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How old are you? ähnelt.
        /// </summary>
        internal static string Q_1 {
            get {
                return ResourceManager.GetString("Q_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How often do you fantasize about the same sex? ähnelt.
        /// </summary>
        internal static string Q_10 {
            get {
                return ResourceManager.GetString("Q_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If your friends decided to party at a gay bar, would you? ähnelt.
        /// </summary>
        internal static string Q_11 {
            get {
                return ResourceManager.GetString("Q_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When a boy touches you (hug or similar), do you like the feeling? ähnelt.
        /// </summary>
        internal static string Q_12 {
            get {
                return ResourceManager.GetString("Q_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you see a good-looking boy, do you notice him and look after him? ähnelt.
        /// </summary>
        internal static string Q_13 {
            get {
                return ResourceManager.GetString("Q_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string Q_14 {
            get {
                return ResourceManager.GetString("Q_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What do you like most about boys? ähnelt.
        /// </summary>
        internal static string Q_15 {
            get {
                return ResourceManager.GetString("Q_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Does your gaydar work? Do you recognize other gay people? ähnelt.
        /// </summary>
        internal static string Q_16 {
            get {
                return ResourceManager.GetString("Q_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imagine someone of the same sex comes up to you and kisses you. What&apos;s your reaction? ähnelt.
        /// </summary>
        internal static string Q_17 {
            get {
                return ResourceManager.GetString("Q_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When a handsome couple comes toward you, who do you notice first? ähnelt.
        /// </summary>
        internal static string Q_18 {
            get {
                return ResourceManager.GetString("Q_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you see a gay couple kissing, what do you feel? ähnelt.
        /// </summary>
        internal static string Q_19 {
            get {
                return ResourceManager.GetString("Q_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why are you taking this test? ähnelt.
        /// </summary>
        internal static string Q_2 {
            get {
                return ResourceManager.GetString("Q_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A pretty, good friend invites you to her house. What do you think? ähnelt.
        /// </summary>
        internal static string Q_20 {
            get {
                return ResourceManager.GetString("Q_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;re at a party and a hot-looking boy approaches you. Do you get a little nervous, excited, or even speechless? ähnelt.
        /// </summary>
        internal static string Q_21 {
            get {
                return ResourceManager.GetString("Q_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If your partner offered you a threesome with a same-sex partner, would you? ähnelt.
        /// </summary>
        internal static string Q_22 {
            get {
                return ResourceManager.GetString("Q_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever been afraid or reluctant to tell your family about your sexual or romantic preferences? ähnelt.
        /// </summary>
        internal static string Q_23 {
            get {
                return ResourceManager.GetString("Q_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you feel comfortable talking about your sexual identity or having someone ask you about it? ähnelt.
        /// </summary>
        internal static string Q_24 {
            get {
                return ResourceManager.GetString("Q_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What do you do when your friends talk homophobic stuff? ähnelt.
        /// </summary>
        internal static string Q_25 {
            get {
                return ResourceManager.GetString("Q_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever worn clothes of the opposite sex, or fantasized about it? ähnelt.
        /// </summary>
        internal static string Q_26 {
            get {
                return ResourceManager.GetString("Q_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever dreamed of being romantically involved with a person of the same sex? ähnelt.
        /// </summary>
        internal static string Q_27 {
            get {
                return ResourceManager.GetString("Q_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you joined an online LGBT community anonymously? ähnelt.
        /// </summary>
        internal static string Q_28 {
            get {
                return ResourceManager.GetString("Q_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever watched same-sex pornography? ähnelt.
        /// </summary>
        internal static string Q_29 {
            get {
                return ResourceManager.GetString("Q_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever looked at a person of the same sex and felt attracted in a sexual way? ähnelt.
        /// </summary>
        internal static string Q_3 {
            get {
                return ResourceManager.GetString("Q_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What beverage would you drink? ähnelt.
        /// </summary>
        internal static string Q_30 {
            get {
                return ResourceManager.GetString("Q_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pick a singer/songstress. ähnelt.
        /// </summary>
        internal static string Q_31 {
            get {
                return ResourceManager.GetString("Q_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever kissed a person of the same sex? ähnelt.
        /// </summary>
        internal static string Q_4 {
            get {
                return ResourceManager.GetString("Q_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever kissed a person of the opposite sex? ähnelt.
        /// </summary>
        internal static string Q_5 {
            get {
                return ResourceManager.GetString("Q_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever seen a boy or man, or even had contact with him, and then thought about him for hours and days afterwards - his face or voice echoed in your head for a long time. ähnelt.
        /// </summary>
        internal static string Q_6 {
            get {
                return ResourceManager.GetString("Q_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfortunately, he never showed up again? ähnelt.
        /// </summary>
        internal static string Q_7 {
            get {
                return ResourceManager.GetString("Q_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have you ever had sex fantasies with the opposite sex? ähnelt.
        /// </summary>
        internal static string Q_8 {
            get {
                return ResourceManager.GetString("Q_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How flexible and tolerant are you in choosing your sexual partners? ähnelt.
        /// </summary>
        internal static string Q_9 {
            get {
                return ResourceManager.GetString("Q_9", resourceCulture);
            }
        }
    }
}
