//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonJT_Web.Resources.Gender.QuA.Gender {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonJT_Web.Resources.Gender.QuA.Gender.DE", typeof(DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erst der Kopf und danach die Arme. ähnelt.
        /// </summary>
        internal static string A_1_1 {
            get {
                return ResourceManager.GetString("A_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erst die Arme und dann über den Kopf. ähnelt.
        /// </summary>
        internal static string A_1_2 {
            get {
                return ResourceManager.GetString("A_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gibt noch einen Weg. ähnelt.
        /// </summary>
        internal static string A_1_3 {
            get {
                return ResourceManager.GetString("A_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_1_4 {
            get {
                return ResourceManager.GetString("A_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_10_1 {
            get {
                return ResourceManager.GetString("A_10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -
        ///-
        ///-
        ///-
        ///- ähnelt.
        /// </summary>
        internal static string A_10_2 {
            get {
                return ResourceManager.GetString("A_10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_10_3 {
            get {
                return ResourceManager.GetString("A_10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_10_4 {
            get {
                return ResourceManager.GetString("A_10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_11_1 {
            get {
                return ResourceManager.GetString("A_11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_11_2 {
            get {
                return ResourceManager.GetString("A_11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_11_3 {
            get {
                return ResourceManager.GetString("A_11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_11_4 {
            get {
                return ResourceManager.GetString("A_11_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_12_1 {
            get {
                return ResourceManager.GetString("A_12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_12_2 {
            get {
                return ResourceManager.GetString("A_12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_12_3 {
            get {
                return ResourceManager.GetString("A_12_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_12_4 {
            get {
                return ResourceManager.GetString("A_12_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_13_1 {
            get {
                return ResourceManager.GetString("A_13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_13_2 {
            get {
                return ResourceManager.GetString("A_13_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_13_3 {
            get {
                return ResourceManager.GetString("A_13_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_13_4 {
            get {
                return ResourceManager.GetString("A_13_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_14_1 {
            get {
                return ResourceManager.GetString("A_14_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_14_2 {
            get {
                return ResourceManager.GetString("A_14_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_14_3 {
            get {
                return ResourceManager.GetString("A_14_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_14_4 {
            get {
                return ResourceManager.GetString("A_14_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_15_1 {
            get {
                return ResourceManager.GetString("A_15_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_15_2 {
            get {
                return ResourceManager.GetString("A_15_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_15_3 {
            get {
                return ResourceManager.GetString("A_15_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_15_4 {
            get {
                return ResourceManager.GetString("A_15_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_16_1 {
            get {
                return ResourceManager.GetString("A_16_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_16_2 {
            get {
                return ResourceManager.GetString("A_16_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_16_3 {
            get {
                return ResourceManager.GetString("A_16_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_16_4 {
            get {
                return ResourceManager.GetString("A_16_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die härteren Sachen  ähnelt.
        /// </summary>
        internal static string A_17_1 {
            get {
                return ResourceManager.GetString("A_17_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wein, Sekt, Cocktail ähnelt.
        /// </summary>
        internal static string A_17_2 {
            get {
                return ResourceManager.GetString("A_17_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bier ähnelt.
        /// </summary>
        internal static string A_17_3 {
            get {
                return ResourceManager.GetString("A_17_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_17_4 {
            get {
                return ResourceManager.GetString("A_17_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_18_1 {
            get {
                return ResourceManager.GetString("A_18_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_18_2 {
            get {
                return ResourceManager.GetString("A_18_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_18_3 {
            get {
                return ResourceManager.GetString("A_18_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_18_4 {
            get {
                return ResourceManager.GetString("A_18_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_19_1 {
            get {
                return ResourceManager.GetString("A_19_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_19_2 {
            get {
                return ResourceManager.GetString("A_19_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_19_3 {
            get {
                return ResourceManager.GetString("A_19_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_19_4 {
            get {
                return ResourceManager.GetString("A_19_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich bin sehr empathie voll. ähnelt.
        /// </summary>
        internal static string A_2_1 {
            get {
                return ResourceManager.GetString("A_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hin und wieder. ähnelt.
        /// </summary>
        internal static string A_2_2 {
            get {
                return ResourceManager.GetString("A_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string A_2_3 {
            get {
                return ResourceManager.GetString("A_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_2_4 {
            get {
                return ResourceManager.GetString("A_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_20_1 {
            get {
                return ResourceManager.GetString("A_20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_20_2 {
            get {
                return ResourceManager.GetString("A_20_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_20_3 {
            get {
                return ResourceManager.GetString("A_20_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_20_4 {
            get {
                return ResourceManager.GetString("A_20_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_21_1 {
            get {
                return ResourceManager.GetString("A_21_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_21_2 {
            get {
                return ResourceManager.GetString("A_21_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_21_3 {
            get {
                return ResourceManager.GetString("A_21_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_21_4 {
            get {
                return ResourceManager.GetString("A_21_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_22_1 {
            get {
                return ResourceManager.GetString("A_22_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_22_2 {
            get {
                return ResourceManager.GetString("A_22_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_22_3 {
            get {
                return ResourceManager.GetString("A_22_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_22_4 {
            get {
                return ResourceManager.GetString("A_22_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_23_1 {
            get {
                return ResourceManager.GetString("A_23_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_23_2 {
            get {
                return ResourceManager.GetString("A_23_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_23_3 {
            get {
                return ResourceManager.GetString("A_23_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_23_4 {
            get {
                return ResourceManager.GetString("A_23_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich pinkel mal im sitzen mal im stehen ähnelt.
        /// </summary>
        internal static string A_24_1 {
            get {
                return ResourceManager.GetString("A_24_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich pinkel im stehen. ähnelt.
        /// </summary>
        internal static string A_24_2 {
            get {
                return ResourceManager.GetString("A_24_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich pinkel im sitzen. ähnelt.
        /// </summary>
        internal static string A_24_3 {
            get {
                return ResourceManager.GetString("A_24_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_24_4 {
            get {
                return ResourceManager.GetString("A_24_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oft ähnelt.
        /// </summary>
        internal static string A_3_1 {
            get {
                return ResourceManager.GetString("A_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selten ähnelt.
        /// </summary>
        internal static string A_3_2 {
            get {
                return ResourceManager.GetString("A_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nie ähnelt.
        /// </summary>
        internal static string A_3_3 {
            get {
                return ResourceManager.GetString("A_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_3_4 {
            get {
                return ResourceManager.GetString("A_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich suche mir einen großeren Parkplatz. ähnelt.
        /// </summary>
        internal static string A_4_1 {
            get {
                return ResourceManager.GetString("A_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich versuche vorsichtig einzuparken. ähnelt.
        /// </summary>
        internal static string A_4_2 {
            get {
                return ResourceManager.GetString("A_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich parke ohne Probleme ein. ähnelt.
        /// </summary>
        internal static string A_4_3 {
            get {
                return ResourceManager.GetString("A_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_4_4 {
            get {
                return ResourceManager.GetString("A_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string A_5_1 {
            get {
                return ResourceManager.GetString("A_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string A_5_2 {
            get {
                return ResourceManager.GetString("A_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teilweise ähnelt.
        /// </summary>
        internal static string A_5_3 {
            get {
                return ResourceManager.GetString("A_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_5_4 {
            get {
                return ResourceManager.GetString("A_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich singe oft ähnelt.
        /// </summary>
        internal static string A_6_1 {
            get {
                return ResourceManager.GetString("A_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich singe ab und zu ähnelt.
        /// </summary>
        internal static string A_6_2 {
            get {
                return ResourceManager.GetString("A_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich singe nie ähnelt.
        /// </summary>
        internal static string A_6_3 {
            get {
                return ResourceManager.GetString("A_6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_6_4 {
            get {
                return ResourceManager.GetString("A_6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mit dem Kopf ähnelt.
        /// </summary>
        internal static string A_7_1 {
            get {
                return ResourceManager.GetString("A_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intuition ähnelt.
        /// </summary>
        internal static string A_7_2 {
            get {
                return ResourceManager.GetString("A_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_7_3 {
            get {
                return ResourceManager.GetString("A_7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_7_4 {
            get {
                return ResourceManager.GetString("A_7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich versuche erst mal alleine den Weg zu finden. ähnelt.
        /// </summary>
        internal static string A_8_1 {
            get {
                return ResourceManager.GetString("A_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich frage direkt jemanden nach dem Weg. ähnelt.
        /// </summary>
        internal static string A_8_2 {
            get {
                return ResourceManager.GetString("A_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_8_3 {
            get {
                return ResourceManager.GetString("A_8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free ähnelt.
        /// </summary>
        internal static string A_8_4 {
            get {
                return ResourceManager.GetString("A_8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_9_1 {
            get {
                return ResourceManager.GetString("A_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_9_2 {
            get {
                return ResourceManager.GetString("A_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_9_3 {
            get {
                return ResourceManager.GetString("A_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string A_9_4 {
            get {
                return ResourceManager.GetString("A_9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 24 ähnelt.
        /// </summary>
        internal static string MaxQuestion {
            get {
                return ResourceManager.GetString("MaxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie ziehst du deinen Pullover an? ähnelt.
        /// </summary>
        internal static string Q_1 {
            get {
                return ResourceManager.GetString("Q_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Freund/eine Freundin hat ein persönliches Problem und möchte es mit dir darüber reden. Wie reagierst du? ähnelt.
        /// </summary>
        internal static string Q_10 {
            get {
                return ResourceManager.GetString("Q_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie streitest du gewöhnlich? ähnelt.
        /// </summary>
        internal static string Q_11 {
            get {
                return ResourceManager.GetString("Q_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wann machst du wichtige Besorgungen? ähnelt.
        /// </summary>
        internal static string Q_12 {
            get {
                return ResourceManager.GetString("Q_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was regt dich am meisten auf, wenn du mit jemandem streitest? ähnelt.
        /// </summary>
        internal static string Q_13 {
            get {
                return ResourceManager.GetString("Q_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie gut kannst du tanzen? ähnelt.
        /// </summary>
        internal static string Q_14 {
            get {
                return ResourceManager.GetString("Q_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liebe ist für mich.... ähnelt.
        /// </summary>
        internal static string Q_15 {
            get {
                return ResourceManager.GetString("Q_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie trinkst du deinen Kaffe? ähnelt.
        /// </summary>
        internal static string Q_16 {
            get {
                return ResourceManager.GetString("Q_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was trinkst du? ähnelt.
        /// </summary>
        internal static string Q_17 {
            get {
                return ResourceManager.GetString("Q_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welche Serie würdest du eher schauen? ähnelt.
        /// </summary>
        internal static string Q_18 {
            get {
                return ResourceManager.GetString("Q_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partnerwahl Frage... ähnelt.
        /// </summary>
        internal static string Q_19 {
            get {
                return ResourceManager.GetString("Q_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie steht es mit deiner Empathie? ähnelt.
        /// </summary>
        internal static string Q_2 {
            get {
                return ResourceManager.GetString("Q_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inwiefern sind deine Haare ein Thema für dich? ähnelt.
        /// </summary>
        internal static string Q_20 {
            get {
                return ResourceManager.GetString("Q_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kannst du nähen, stricken, oder häckeln? ähnelt.
        /// </summary>
        internal static string Q_21 {
            get {
                return ResourceManager.GetString("Q_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast herausgefunden, dass dein Freund  hinter deinem Rücken über dich redet. Was tust du? ähnelt.
        /// </summary>
        internal static string Q_22 {
            get {
                return ResourceManager.GetString("Q_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wofür würdest du am Ende des Monats das Geld ausgeben, wenn du noch genügend zur Verfügung hättest? ähnelt.
        /// </summary>
        internal static string Q_23 {
            get {
                return ResourceManager.GetString("Q_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pinkelst du im sitzen oder im stehen? ähnelt.
        /// </summary>
        internal static string Q_24 {
            get {
                return ResourceManager.GetString("Q_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übermannen dich oft deine Tränen, bei traurigen Filmen oder bei Hochzeitsreden oder Abschieden? ähnelt.
        /// </summary>
        internal static string Q_3 {
            get {
                return ResourceManager.GetString("Q_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast eine Parklücke gefunden, die allerdings recht eng ist und in die du rückwärts einparken müßten. Wie verhaltest du dich? ähnelt.
        /// </summary>
        internal static string Q_4 {
            get {
                return ResourceManager.GetString("Q_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast gerade einen neuen Song von deinem Lieblingssänger gehört. Kannst du das Lied nachsingen? ähnelt.
        /// </summary>
        internal static string Q_5 {
            get {
                return ResourceManager.GetString("Q_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sings du oft und gerne bei Lieder mit und versuchst es bestmöglichst wie das Original zu singen? ähnelt.
        /// </summary>
        internal static string Q_6 {
            get {
                return ResourceManager.GetString("Q_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie triffst du die meisten Entscheidungen? ähnelt.
        /// </summary>
        internal static string Q_7 {
            get {
                return ResourceManager.GetString("Q_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast dich verfahren und dein Navi streikt. Was tust du? ähnelt.
        /// </summary>
        internal static string Q_8 {
            get {
                return ResourceManager.GetString("Q_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du möchten Ihren Urlaub auf dem Land verbringen, doch dein Partner/deine Partnerin möchte gerne ans Meer. Wie versuchst du, ihn/sie davon zu überzeugen, dass dein Reiseziel das bessere ist? ähnelt.
        /// </summary>
        internal static string Q_9 {
            get {
                return ResourceManager.GetString("Q_9", resourceCulture);
            }
        }
    }
}
