//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonJT_Web.Resources.Error {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonJT_Web.Resources.Error.DE", typeof(DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück zur Startseite ähnelt.
        /// </summary>
        internal static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versuche die Seite mit F5 neu zu laden, oder gehe eine Seite zurück und versuche es erneut. Sollte der Fehler danach immernoch erscheinen, kannst du diesen Fehler gerne an mich schicken und ich schaue mir die Sache genauer an. ähnelt.
        /// </summary>
        internal static string BadRequest_Description {
            get {
                return ResourceManager.GetString("BadRequest_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tut mir leid, doch bei deiner Anfrage an den Server ist leider wohl ein Problem aufgetreten! ähnelt.
        /// </summary>
        internal static string BadRequest_Heading {
            get {
                return ResourceManager.GetString("BadRequest_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Naja für diesen Fehler, gibt es keine Behebung. Es ist ja gewollt, dass diese Dateien keinen Zugriff gewährt ist. ähnelt.
        /// </summary>
        internal static string Forbidden_Description {
            get {
                return ResourceManager.GetString("Forbidden_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tut mir leid, doch du versuchst gerade auf unerlaubte Dateien zuzugreifen! ähnelt.
        /// </summary>
        internal static string Forbidden_Heading {
            get {
                return ResourceManager.GetString("Forbidden_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tut mir leid, doch dieser Fehler scheint mir oder dem System gerade wohl nicht bekannt zu sein. Du kannst mir diesen Fehler gerne schicken und ich schaue mir die Sache genauer an. ähnelt.
        /// </summary>
        internal static string Index_Description {
            get {
                return ResourceManager.GetString("Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startseite - Unbehandelter Fehler! ähnelt.
        /// </summary>
        internal static string Index_Heading {
            get {
                return ResourceManager.GetString("Index_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string InternalServerError_Description {
            get {
                return ResourceManager.GetString("InternalServerError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tut mir leid, doch es ist ein interner Serverfehler aufgetreten! ähnelt.
        /// </summary>
        internal static string InternalServerError_Heading {
            get {
                return ResourceManager.GetString("InternalServerError_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für diesen Fehler kann es gleich mehere Gründe haben. Entweder wurde diese seite gelöscht, du versucht diese Seite gerade per manuelle eingabe der URL und hast dich verschrieben oder naja der Entwickler, also ich habe scheiße gebaut :D ähnelt.
        /// </summary>
        internal static string NotFound_Description {
            get {
                return ResourceManager.GetString("NotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tut mir leid, doch diese Seite konnte leider nicht gefunden werden. ähnelt.
        /// </summary>
        internal static string NotFound_Heading {
            get {
                return ResourceManager.GetString("NotFound_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um den Fehler zu beheben, melde dich bitte an. Solltest du noch kein Konto besitzen, kannst du dir jederzeit ein kostenloses Konto erstellen. Sollte der Fehler danach immernoch erscheinen, kannst du diesen Fehler gerne an mich schicken und ich schaue mir die Sache genauer an. ähnelt.
        /// </summary>
        internal static string Unauthorized_Description {
            get {
                return ResourceManager.GetString("Unauthorized_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tut mir leid, doch entweder bist du nicht angemeldet, oder besitzt nicht die benötigten Rechte! ähnelt.
        /// </summary>
        internal static string Unauthorized_Heading {
            get {
                return ResourceManager.GetString("Unauthorized_Heading", resourceCulture);
            }
        }
    }
}
