//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonJT_Web.Resources.Error {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonJT_Web.Resources.Error.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to Home ähnelt.
        /// </summary>
        internal static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Try to reload the page with F5, or go back one page and try again. If the error still appears after that, feel free to send this error to me and I&apos;ll take a closer look. ähnelt.
        /// </summary>
        internal static string BadRequest_Description {
            get {
                return ResourceManager.GetString("BadRequest_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but there seems to be a problem with your request to the server! ähnelt.
        /// </summary>
        internal static string BadRequest_Heading {
            get {
                return ResourceManager.GetString("BadRequest_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Well, for this error, there is no fix. It is intentional that these files are not granted access. ähnelt.
        /// </summary>
        internal static string Forbidden_Description {
            get {
                return ResourceManager.GetString("Forbidden_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but you are trying to access unauthorized files right now! ähnelt.
        /// </summary>
        internal static string Forbidden_Heading {
            get {
                return ResourceManager.GetString("Forbidden_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but this error seems to be unknown to me or the system right now. You are welcome to send me this error and I will take a closer look. ähnelt.
        /// </summary>
        internal static string Index_Description {
            get {
                return ResourceManager.GetString("Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home - Untreated error! ähnelt.
        /// </summary>
        internal static string Index_Heading {
            get {
                return ResourceManager.GetString("Index_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string InternalServerError_Description {
            get {
                return ResourceManager.GetString("InternalServerError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but an internal server error has occurred! ähnelt.
        /// </summary>
        internal static string InternalServerError_Heading {
            get {
                return ResourceManager.GetString("InternalServerError_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There can be several reasons for this error. Either this page was deleted, you are trying this page by manually entering the URL and have made a mistake or well the developer, so I fucked up :D ähnelt.
        /// </summary>
        internal static string NotFound_Description {
            get {
                return ResourceManager.GetString("NotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but this page could not be found. ähnelt.
        /// </summary>
        internal static string NotFound_Heading {
            get {
                return ResourceManager.GetString("NotFound_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To fix the error, please log in. If you don&apos;t have an account yet, you can always create one for free. If the error still appears after that, you are welcome to send this error to me and I will take a closer look. ähnelt.
        /// </summary>
        internal static string Unauthorized_Description {
            get {
                return ResourceManager.GetString("Unauthorized_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, but either you are not logged in, or do not have the required rights! ähnelt.
        /// </summary>
        internal static string Unauthorized_Heading {
            get {
                return ResourceManager.GetString("Unauthorized_Heading", resourceCulture);
            }
        }
    }
}
