//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonJT_Web.Resources.Gender.Advisor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonJT_Web.Resources.Gender.Advisor.DE", typeof(DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h1&gt;Ratgeber für Freunde&lt;/h1&gt;
        ///
        ///    &lt;h4&gt;Wie verhalte ich mich, wenn mein Freund sich outet?&lt;/h4&gt;
        ///
        ///    &lt;p&gt;
        ///        Bei Freunden einen Rat zu geben ist etwas schwieriger, den ich finde da braucht man keinen Rat zu geben.
        ///        Zu mir haben auch schon Freunde oder Kollegen gesagt, dass sie schwul sind.
        ///        Darauf gabs von mir meistens als Antwort, das habe ich mir schon gedacht. Ich fande den verwunderten Blick immer lustig,
        ///        habe aber der Person nicht gesagt, dass ich ebenfalls schwul bin. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h1&gt;Ratgeber für Eltern und Verwandte&lt;/h1&gt;
        ///
        ///    &lt;h4&gt;Wie verhalte ich mich, wenn mein Kind sich outet?&lt;/h4&gt;
        ///
        ///    &lt;p&gt;
        ///        Wenn das eigene Kind sich outet, ist das für viele Eltern erst mal ein Schock!
        ///        Die schlechteste Reaktion in diesem Moment, ist wütend zu werden.
        ///        Klar, ist es nicht einfach, diese Nachricht erst einmal zu verarbeiten,
        ///        doch es war auch für ihr Kind nicht einfach, ihnen diese Nachricht zu überbringen.
        ///        Sollte es im Streit ausversehen heraus gerutsch [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h1&gt;Ratgeber vor dem Outing&lt;/h1&gt;
        ///
        ///    &lt;h4&gt;Was soll ich machen? Ich weiß nicht weiter...&lt;/h4&gt;
        ///
        ///    &lt;p&gt;
        ///        Wenn du dir sicher bist, was du möchtest und wo du hin möchtest, dann haben wir schon
        ///        einmal den ersten Schritt. Meine nächste Frage wäre, ob du etwas zuhause vor deinen
        ///        Eltern versteckst, was damit zusammen hängt. Wenn ja, wie fühlt es sich an es immer
        ///        verstecken zu müssen? Es kann auch sein, dass es Unterhaltungen gab, wie z.B. über
        ///        eine Freundin und du die [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
    }
}
