//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonJT_Web.Resources.Gender.Advisor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonJT_Web.Resources.Gender.Advisor.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h1&gt;Guide for friends&lt;/h1&gt;
        ///
        ///    &lt;h4&gt;How do I act when my friend comes out?&lt;/h4&gt;
        ///
        ///    &lt;p&gt;
        ///        With friends to give an advice is a little more difficult, the I find there you do not need to give advice.
        ///        To me, friends or colleagues have already said that they are gay.
        ///        On it gave from me mostly as an answer, I have already thought. I always found the astonished look funny,
        ///        but I did not tell the person that I am also gay.
        ///        For many people who come out, many contacts  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h1&gt;Guide for parents and relatives&lt;/h1&gt;.
        ///
        ///    &lt;h4&gt;How do I act when my child comes out?&lt;/h4&gt;
        ///
        ///    &lt;p&gt;
        ///        When your child comes out, it comes as a shock to many parents at first!
        ///        The worst reaction in this moment, is to get angry.
        ///        Sure, it is not easy to process this news first,
        ///        But it was also not easy for their child to give them this news.
        ///        If it accidentally slipped out in the argument, it can be an even bigger shock for your child.
        ///        shock.
        ///        S [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h1&gt;Guide before coming out&lt;/h1&gt;.
        ///
        ///    &lt;h4&gt;What should I do? I&apos;m at a loss&lt;/h4&gt;.
        ///
        ///    &lt;p&gt;
        ///        If you are sure what you want and where you want to go, then we already have
        ///        the first step. My next question would be, are you hiding something at home from your
        ///        from your parents that is related to this. If so, how does it feel to always have to hide it?
        ///        to have to hide it? It could also be that there were conversations, like about
        ///        a friend and you lied to that person. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
    }
}
