//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonJT_Web.Resources.CreatorProfile {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonJT_Web.Resources.CreatorProfile.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string A_1 {
            get {
                return ResourceManager.GetString("A_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;&lt;b&gt;Name:&lt;/b&gt; Jason&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;Nick Name:&lt;/b&gt; DarkSide_Wolf | DarkSideWolf_JT&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;Age:&lt;/b&gt; 22 (09/20/1998)&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;Sex:&lt;/b&gt; male (gay)&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;Height:&lt;/b&gt; 1,80m&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;Weight:&lt;/b&gt; -&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;Occupation:&lt;/b&gt; computer scientist&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;Hobbies:&lt;/b&gt; meeting friends, partying, climbing, swimming, gambling, programming&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;kind:&lt;/b&gt; kind, funny, reserved, emotional, helpful, affectionate&lt;/p&gt;
        ///        &lt;p&gt;&lt;b&gt;Status:&lt;/b&gt;  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;h2&gt;My Outing&lt;/h2&gt;
        ///            &lt;br /&gt;
        ///
        ///            &lt;p class=&quot;OutingContent&quot;&gt;
        ///                I came out to my mother on 6/29/2021, as they call it (at the age of 22yo). 
        ///                I had been planning to tell her in some way for about 5 years, but I wanted to wait for the right time. 
        ///                An idea, or let&apos;s say an approach how to tell her, I also did not have. 
        ///                But since I had to admit to m [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MyOuting {
            get {
                return ResourceManager.GetString("MyOuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;img src=&quot;~/src/JasonJT/FurryLove.jpg&quot; class=&quot;ProfilePicture PP3 col&quot; /&gt;
        ///            &lt;img src=&quot;~/src/JasonJT/Logo.jpg&quot; class=&quot;ProfilePicture PP1 col&quot; /&gt;
        ///            &lt;img src=&quot;~/src/JasonJT/DarkWolfFurry.png&quot; class=&quot;ProfilePicture PP2 col&quot; /&gt; ähnelt.
        /// </summary>
        internal static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Q_1 {
            get {
                return ResourceManager.GetString("Q_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;h2&gt;F&amp;A&lt;/h2&gt;
        ///            &lt;br /&gt;
        ///
        ///            &lt;div class=&quot;info&quot;&gt;
        ///                &lt;b&gt;What am I up for?&lt;/b&gt;
        ///                &lt;p&gt;Many things, but not everything, but really any mischief!&lt;/p&gt;
        ///            &lt;/div&gt;
        ///
        ///            &lt;div class=&quot;info&quot;&gt;
        ///                &lt;b&gt;What is the most important thing in my life?&lt;/b&gt;
        ///                &lt;p&gt;People who mean something to you and are there for you when you need them.&lt;/p&gt;
        ///            &lt;/div&gt; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string QaA {
            get {
                return ResourceManager.GetString("QaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            &lt;h2&gt;Socials&lt;/h2&gt;
        ///            &lt;br /&gt;
        ///
        ///            &lt;div class=&quot;container&quot;&gt;
        ///                &lt;div class=&quot;row&quot;&gt;
        ///
        ///                    &lt;div class=&quot;col&quot;&gt;
        ///                        &lt;div class=&quot;container&quot;&gt;
        ///                            &lt;div class=&quot;row&quot;&gt;
        ///                                &lt;div class=&quot;col&quot;&gt;
        ///                                    &lt;a class=&quot;SocialLink&quot; href=&quot;https://discordapp.com/users/246277810274959360&quot;&gt; &lt;img class=&quot;Social [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Socials {
            get {
                return ResourceManager.GetString("Socials", resourceCulture);
            }
        }
    }
}
